### ISSUE TITLE
prevent unnecessary changes from being committed

### ISSUE THREAD

**Issue by SimHoZebs** [ipod1g/flutter_test#1]
Update gitignore using this:
https://github.com/flutter/flutter/blob/master/.gitignore

If git does not update, refer to this as well:
https://stackoverflow.com/questions/25436312/gitignore-not-working

**Comment by ipod1g** [comment]
Thanks for paying attention!

**Comment by SimHoZebs** [comment]
FYI, you can close issues when you commit the changes: https://github.blog/2013-01-22-closing-issues-via-commit-messages/
